name: "Run Tests on Reviewer Requested"
on:
  pull_request:
    types: [review_requested]

jobs:
  get-pr-commit-data:
    name: Get Latest PR Commit SHA
    if: github.event.pull_request.requested_reviewers && contains(github.event.pull_request.requested_reviewers, 'cnocon')
    runs-on: ubuntu-latest
    outputs:
      pr-sha: ${{ steps.pr-comment-commit-data.outputs.head_sha }}
      pr-ref: ${{ steps.pr-comment-commit-data.outputs.head_ref }}
    steps:
      - name: Get Comment Branch SHA
        uses: xt0rted/pull-request-comment-branch@v1
        id: pr-comment-commit-data
      - run: echo '${{steps.pr-comment-commit-data.outputs.head_ref }}'
  tests-job:
    name: Tests Job
    runs-on: ubuntu-latest
    needs: get-pr-commit-data
    if: github.event.pull_request.requested_reviewers && contains(github.event.pull_request.requested_reviewers, 'cnocon')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.get-pr-commit-data.outputs.pr-ref }}
          sha: ${{ needs.get-pr-commit-data.outputs.pr-sha }}
      - uses: actions/setup-node@v4
        with:
          ref: ${{ needs.get-pr-commit-data.outputs.pr-ref }}
          sha: ${{ needs.get-pr-commit-data.outputs.pr-sha }}
          node-version: '20'
  
  # other-job:
  #   name: Other Job
  #   if: github.event.pull_request.requested_reviewers && contains(github.event.pull_request.requested_reviewers, 'cnocon')
  #   runs-on: ubuntu-latest
  #   needs: [get-pr-commit-data, tests-job]
  #   steps:
  #     - name: get the one latest&last sha # get the last commit sha in pull_Requst
  #       env:
  #         PRSHA: ${{ needs.get-pr-commit-data.outputs.pr-sha}} 
  #       run: |
  #         URL=${{ github.event.issue.pull_request.url }}/commits
  #         echo "PRSHA=${{ needs.get-pr-commit-data.outputs.pr-sha }}"
  #     - name: echo PRSHA # check the lastest SHA
  #       env:
  #         PRSHA: ${{ needs.get-pr-commit-data.outputs.pr-sha}} 
  #       run: |
  #         echo $PRSHA
  #     - name: create the status # create the status on the lastest commit sha from pull request
  #       env:
  #         PRSHA: ${{ needs.get-pr-commit-data.outputs.pr-sha}}
  #       run: |
  #         curl -X POST -u  \
  #         -H "Accept: application/vnd.github+json" \
  #         -H "Authorization: Bearer ${{ secrets.REPO_ACCESS_TOKEN }}" \
  #         -H "X-GitHub-Api-Version: 2022-11-28" \
  #         https://api.github.com/repos/citybasecnocon/github-actions-testing/statuses/${{ needs.get-pr-commit-data.outputs.pr-sha }} \
  #         -d '{"state":${{ job.status }},"target_url":"https://api.github.com/repos/citybasecnocon/github-actions-testing/commits/${{ needs.get-pr-commit-data.outputs.pr-sha }}/status","description":"The build was a ${{ job.status }}!","context":${{ needs.get-pr-commit-data.outputs.pr-ref }}}'

  
  # # other-job:
  # #   name: Other Job
  # #   if: github.event.issue.pull_request && contains(github.event.comment.body, '/test')
  # #   runs-on: ubuntu-latest
  # #   needs: [get-pr-commit-data, tests-job]
  # #   steps:
  # #     - name: Update Commit Status to Job Status
  # #       uses: myrotvorets/set-commit-status-action@master
  # #       if: always()
  # #       with:
  # #         status: ${{ job.status }}
  # #         sha: ${{ needs.get-pr-commit-data.outputs.pr-sha }}
  # #         token: ${{ secrets.REPO_ACCESS_TOKEN }}