name: "Run E2E Tests on Comment"
on: [push]

jobs:
  get-pr-commit-data:
    name: Get Latest PR Commit SHA
    runs-on: ubuntu-latest
    outputs:
      pr-sha: ${{ github.sha }}
      pr-ref: ${{ github.ref }}
    steps:
      - name: Run stuff
        run: echo ${{ github.ref }}

  tests-job:
    name: Tests Job
    runs-on: ubuntu-latest
    needs: get-pr-commit-data
    steps:
      - name: Tests Step
        run: echo "Tests step for ${{ github.sha }}"
  
  other-job:
    name: Other Job
    runs-on: ubuntu-latest
    needs: [get-pr-commit-data, tests-job]
    steps:
      - name: Update Commit Status to Job Status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          status: ${{ job.status }}
          sha: ${{ github.sha }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
