name: "Run Tests on Comment"
on: [push]

jobs:
  
  get-pr-commit-data:
    name: Get Latest PR Commit SHA
    runs-on: ubuntu-latest
    outputs:
      pr-sha: ${{ steps.pr-comment-commit-data.outputs.head_sha }}
      pr-ref: ${{ steps.pr-comment-commit-data.outputs.head_ref }}
    steps:
      - name: Get Comment Branch SHA
        uses: xt0rted/pull-request-comment-branch@v1
        id: pr-comment-commit-data

  tests-job-secondary:
    name: Tests Job
    runs-on: ubuntu-latest
    steps:
      - name: Tests Step
        run: echo "Tests step for ${{ needs.get-pr-commit-data.outputs.pr-ref }}"
      - name: Failure Step
        run: echo ref -  ${{ needs.get-pr-commit-data.outputs.pr-ref }}
  
  # other-job:
  #   name: Other Job
  #   runs-on: ubuntu-latest
  #   needs: [tests-job-secondary]
  #   steps:
  #     - name: Update Commit Status to Job Status
  #       uses: myrotvorets/set-commit-status-action@master
  #       if: always()
  #       with:
  #         status: ${{ job.status }}
  #         sha: ${{ github.sha }}
  #         token: ${{ secrets.REPO_ACCESS_TOKEN }}
