name: "Run Tests on Comment"
on: [push]

jobs:
  tests-job-secondary:
    name: Tests Job
    runs-on: ubuntu-latest
    steps:
      - name: Tests Step
        run: echo "Tests step for ${{ github.sha }}"
  
  # other-job:
  #   name: Other Job
  #   runs-on: ubuntu-latest
  #   needs: [get-pr-commit-data, tests-job]
  #   steps:
  #     - name: Update Commit Status to Job Status
  #       uses: myrotvorets/set-commit-status-action@master
  #       if: always()
  #       with:
  #         status: ${{ job.status }}
  #         sha: ${{ github.sha }}
  #         token: ${{ secrets.REPO_ACCESS_TOKEN }}
