name: "Run Tests on Comment"
on:
  pull_request:
    types: [synchronize]


jobs:
  get-pr-commit-data:
    name: Get Latest PR Commit SHA
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest PR Commit SHA Step One
        run: echo github.env - ${{ github.env }}

  tests-job-secondary:
    name: Tests Job
    runs-on: ubuntu-latest
    needs: get-pr-commit-data
    steps:
      - name: Tests Step
        run: echo "Tests step for ${{ needs.get-pr-commit-data.outputs.pr-ref }}"
      - name: Failure Step
        run: echo ref -  ${{ needs.get-pr-commit-data.outputs.pr-ref }}
  
  other-job:
    name: Other Job
    runs-on: ubuntu-latest
    needs: [tests-job-secondary]
    steps:
      - name: Update Commit Status to Job Status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          status: "failure"
          sha: ${{ github.sha }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
