name: "Run Tests on Comment"
on:
  pull_request:
    types: [synchronize]


jobs:
  get-pr-commit-data:
    name: Get Latest PR Commit SHA
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest PR Commit SHA Step One
        run: echo github.env - ${{ github.env }}

  tests-job: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run the action # You would run your tests before this using the output to set state/desc
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{ secrets.REPO_ACCESS_TOKEN }}
        context: 'Test run'
        description: 'Passed'
        state: 'success'
        sha: ${{ github.event.pull_request.head.sha }}
  
  other-job:
    name: Other Job
    runs-on: ubuntu-latest
    needs: [tests-job]
    steps:
      - name: Update Commit Status to Job Status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          status: "failure"
          sha: ${{ github.sha }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
